global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9090']
    metrics_path: '/metrics'

  - job_name: 'reward-service'
    static_configs:
      - targets: ['reward-service:9091']
    metrics_path: '/actuator/prometheus'

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:9092']
    metrics_path: '/metrics'

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:9093']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 