name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, reward-service, transaction-service, analytics-service]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      if: matrix.service == 'user-service'
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Java
      if: matrix.service == 'reward-service'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      if: matrix.service == 'transaction-service' || matrix.service == 'analytics-service'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build and Test User Service
      if: matrix.service == 'user-service'
      working-directory: ./user-service
      run: |
        go mod download
        go test -v ./...

    - name: Build and Test Reward Service
      if: matrix.service == 'reward-service'
      working-directory: ./reward-service
      run: |
        ./mvnw clean test

    - name: Build and Test Transaction Service
      if: matrix.service == 'transaction-service'
      working-directory: ./transaction-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest tests/

    - name: Build and Test Analytics Service
      if: matrix.service == 'analytics-service'
      working-directory: ./analytics-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest tests/ 