name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
  ECR_REPOSITORY: loyalty-platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        working-directory: ./infra
        run: |
          terraform init

      - name: Terraform Plan
        working-directory: ./infra
        run: |
          terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./infra
        run: |
          terraform apply -auto-approve tfplan

      - name: Update Kubernetes Config
        run: |
          aws eks update-kubeconfig --name loyalty-platform-cluster --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          # Update image tags in Kubernetes manifests
          sed -i "s|image: .*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest|g" ./k8s/*.yaml
          
          # Apply Kubernetes manifests
          kubectl apply -f ./k8s/

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/user-service
          kubectl rollout status deployment/reward-service
          kubectl rollout status deployment/transaction-service
          kubectl rollout status deployment/analytics-service 